# Generated by Django 2.0.3 on 2018-03-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='id_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(default='dialog-1-5', max_length=500),
        ),
    ]
