# Generated by Django 2.0.3 on 2018-03-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180328_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_user',
        ),
    ]
