# Generated by Django 2.0.3 on 2018-03-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180328_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts-images'),
        ),
        migrations.AddField(
            model_name='message',
            name='sound',
            field=models.FileField(blank=True, upload_to='musics'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
