# Generated by Django 2.0.2 on 2018-03-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofille',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
