# Generated by Django 2.0.3 on 2018-03-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180323_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofille',
            name='sex',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
