# Generated by Django 2.0.3 on 2018-03-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofille_sex'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofille',
            managers=[
            ],
        ),
    ]
