# Generated by Django 2.0.3 on 2018-03-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180328_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts-images'),
        ),
        migrations.AddField(
            model_name='post',
            name='sound',
            field=models.FileField(blank=True, upload_to='musics'),
        ),
    ]
